import { AsyncState } from "@rue/flask";
import { AnyObject } from "@rue/types";


// export const mathElements = {
//    abs: true,
//    and: true,
//    annotation: true,
//    annotationXML: true,
//    apply: true,
//    approx: true,
//    arccos: true,
//    arccosh: true,
//    arccot: true,
//    arccoth: true,
//    arccsc: true,
//    arccsch: true,
//    arcsec: true,
//    arcsech: true,
//    arcsin: true,
//    arcsinh: true,
//    arctan: true,
//    arctanh: true,
//    arg: true,
//    bvar: true,
//    card: true,
//    cartesianproduct: true,
//    cbytes: true,
//    ceiling: true,
//    ci: true,
//    cn: true,
//    codomain: true,
//    complexes: true,
//    compose: true,
//    condition: true,
//    conjugate: true,
//    cos: true,
//    cosh: true,
//    cot: true,
//    coth: true,
//    cs: true,
//    csc: true,
//    csch: true,
//    csymbol: true,
//    curl: true,
//    declare: true,
//    degree: true,
//    determinant: true,
//    diff: true,
//    divergence: true,
//    divide: true,
//    domain: true,
//    domainofapplication: true,
//    emptyset: true,
//    encoding: true,
//    eq: true,
//    equivalent: true,
//    eulergamma: true,
//    exists: true,
//    exp: true,
//    exponentiale: true,
//    factorial: true,
//    factorof: true,
//    false: true,
//    floor: true,
//    fn: true,
//    forall: true,
//    function: true,
//    gcd: true,
//    geq: true,
//    grad: true,
//    gt: true,
//    ident: true,
//    image: true,
//    imaginary: true,
//    imaginaryi: true,
//    implies: true,
//    in: true,
//    infinity: true,
//    int: true,
//    integers: true,
//    inter: true,
//    interval: true,
//    inverse: true,
//    lambda: true,
//    lcm: true,
//    leq: true,
//    limit: true,
//    list: true,
//    ln: true,
//    log: true,
//    logbase: true,
//    lowlimit: true,
//    lt: true,
//    maction: true,
//    maligngroup: true,
//    malignmark: true,
//    malignscope: true,
//    math: true,
//    matrix: true,
//    matrixrow: true,
//    max: true,
//    mean: true,
//    median: true,
//    menclose: true,
//    merror: true,
//    mfenced: true,
//    mfrac: true,
//    mfraction: true,
//    mglyph: true,
//    mi: true,
//    min: true,
//    minus: true,
//    mlabeledtr: true,
//    mlongdiv: true,
//    mmultiscripts: true,
//    mn: true,
//    mo: true,
//    mode: true,
//    moment: true,
//    mphantom: true,
//    mprescripts: true,
//    mroot: true,
//    mrow: true,
//    ms: true,
//    mscarries: true,
//    mscarry: true,
//    msgroup: true,
//    msline: true,
//    mspace: true,
//    msqrt: true,
//    msrow: true,
//    mstack: true,
//    mstyle: true,
//    msub: true,
//    msubsup: true,
//    msup: true,
//    mtable: true,
//    mtd: true,
//    mtext: true,
//    mtr: true,
//    munder: true,
//    munderover: true,
//    naturalnumbers: true,
//    neq: true,
//    none: true,
//    not: true,
//    notanumber: true,
//    notin: true,
//    notprsubset: true,
//    notsubset: true,
//    or: true,
//    otherwise: true,
//    outerproduct: true,
//    partialdiff: true,
//    pi: true,
//    piece: true,
//    piecewise: true,
//    plus: true,
//    power: true,
//    primes: true,
//    product: true,
//    prsubset: true,
//    quotient: true,
//    rationals: true,
//    real: true,
//    reals: true,
//    reln: true,
//    rem: true,
//    root: true,
//    scalarproduct: true,
//    sdev: true,
//    sec: true,
//    sech: true,
//    selector: true,
//    sep: true,
//    set: true,
//    setdiff: true,
//    sin: true,
//    sinh: true,
//    span: true,
//    sqrt: true,
//    square: true,
//    standarddeviation: true,
//    sub: true,
//    subset: true,
//    sum: true,
//    sup: true,
//    tan: true,
//    tanh: true,
//    tendsto: true,
//    times: true,
//    transpose: true,
//    true: true,
//    union: true,
//    uplimit: true,
//    variance: true,
//    vector: true,
//    vectorproduct: true,
//    xor: true
//  } as const;
 



// const svgTags = {
//    a: true,
//    animate: true,
//    animateMotion: true,
//    animateTransform: true,
//    circle: true,
//    clipPath: true,
//    defs: true,
//    desc: true,
//    ellipse: true,
//    feBlend: true,
//    feColorMatrix: true,
//    feComponentTransfer: true,
//    feComposite: true,
//    feConvolveMatrix: true,
//    feDiffuseLighting: true,
//    feDisplacementMap: true,
//    feDistantLight: true,
//    feDropShadow: true,
//    feFlood: true,
//    feFuncA: true,
//    feFuncB: true,
//    feFuncG: true,
//    feFuncR: true,
//    feGaussianBlur: true,
//    feImage: true,
//    feMerge: true,
//    feMergeNode: true,
//    feMorphology: true,
//    feOffset: true,
//    fePointLight: true,
//    feSpecularLighting: true,
//    feSpotLight: true,
//    feTile: true,
//    feTurbulence: true,
//    filter: true,
//    foreignObject: true,
//    g: true,
//    image: true,
//    line: true,
//    linearGradient: true,
//    marker: true,
//    mask: true,
//    metadata: true,
//    mpath: true,
//    path: true,
//    pattern: true,
//    polygon: true,
//    polyline: true,
//    radialGradient: true,
//    rect: true,
//    script: true,
//    set: true,
//    stop: true,
//    style: true,
//    svg: true,
//    switch: true,
//    symbol: true,
//    text: true,
//    textPath: true,
//    title: true,
//    tspan: true,
//    can: true,
//    view: true,
// } as const;



export function createNSElement(tagName: string, namespace: string) {
   return document.createElementNS(namespace, tagName)
}

export function newXMLNamespace(tagName: string, attributes: AnyObject) {
   return XML_NS[tagName] || attributes?.xmlns
}

const XML_NS = {
   svg: "http://www.w3.org/2000/svg",
   math: "http://www.w3.org/1998/Math/MathML",
} as AnyObject

const XML_NAMESPACE = 'xmlns'

export const [getXMLNamespace, XMLNamespaceStack] = AsyncState<string | undefined>(XML_NAMESPACE)


export function runWithXMLNamespace(Slot: Function, ns: string | undefined){
   try{
      XMLNamespaceStack.push(ns)
      return Slot();
   }
   finally{
      XMLNamespaceStack.pop()
   }
}