import { GenMapping, maybeAddSegment, setSourceContent, toEncodedMap } from '@jridgewell/gen-mapping'
import type { EncodedSourceMap } from '@jridgewell/gen-mapping'
import type { CodeMapping } from '@volar/language-core'

/**
 * generated by GPT-5.4
 * 
 * Limitation: the synthesized map (from transpileNextScript) is boundary-based, not token-perfect, because the existing Volar mappings are span-oriented. That should be a clear improvement for stack traces and debugger location continuity, but if you want higher-fidelity mappings later, the next step is to emit finer-grained mappings during code generation.
 * 
 * 
 * Token-perfect mappings have to be emitted at generation time, not reconstructed afterward.

Right now your generator in 4-generate.ts:2670 records one mapping for an entire emitted span. Then the converter in packages/nextscript/src/sourceMap.ts can only place boundary points for that span. That is why the current map is continuity-correct but not token-perfect.

To make it token-perfect, change the printer so it emits mappings per copied token or per smallest stable fragment.

Split the writer API into source-backed writes and synthetic writes.
Source-backed writes mean: this emitted text came from a precise source slice.
Synthetic writes mean: this text was invented by the transform and should either have no mapping or only a very deliberate anchor.

Record mappings at fragment granularity, not node granularity.
Instead of mapping one whole Identifier, CallExpression, or transformed statement span, map each emitted fragment:
name
dot
property
comma
paren
operator
string literal
keyword
whitespace only if it literally came from source and you care to preserve it

Prefer exact slice copies whenever possible.
The highest-fidelity pattern is:
find the original token span in the source
emit exactly that substring
record a 1:1 mapping for that emitted substring
Whenever output is a verbatim copy from source, token-perfect mapping is straightforward.

For rewritten constructs, map only the pieces that truly correspond.
Example:
if you lower a custom construct into ordinary TSX, do not map the entire generated expansion back to one source span.
Instead:
map generated identifiers or expressions to their exact original token spans
leave inserted punctuation, helper calls, wrappers, and delimiters unmapped if they are synthetic
This gives debuggers and stack traces precise positions without lying about invented code.

Replace the current span-based helper with fragment-based helpers in the printer.
In 4-generate.ts:2670, the current write and mapSpan methods are too coarse. The printer should have methods closer to:
writeFromSource(start, end)
writeGenerated(text)
writeMapped(text, sourceStart, sourceEnd)
beginCompoundMapping only if you really need it
The important shift is that the mapping unit becomes the emitted fragment, not the AST node.

Emit many small Volar mappings, then keep the sourcemap converter simple.
Your converter in packages/nextscript/src/sourceMap.ts is only compensating for coarse input. Once packages/nextscript/src/4-generate.ts emits one mapping per token-sized fragment, the converter can just turn each mapping into one exact sourcemap segment. At that point you no longer need the current boundary heuristic.

A practical rule:
if generated text corresponds to one original lexeme, emit one mapping segment.
if generated text is synthetic, emit no mapping.
if generated text is assembled from several original lexemes, emit several adjacent mappings, one per lexeme.

Concrete example.

Suppose source conceptually contains:
count + 1

If the generator outputs exactly:
count + 1

then emit separate mappings for:
count
+
1

If the generator outputs:
derive(count) + 1

then:
derive and surrounding parentheses are synthetic and usually unmapped
count maps to the original count token

maps if it came from the original +
1 maps to the original 1
That is what token-perfect means in practice: the generated column for each meaningful token points at the exact original token that produced it.

The main tradeoff is cost. You will produce many more mappings, and the printer becomes more disciplined. But this is the correct place to solve the problem. Post-processing in packages/nextscript/src/sourceMap.ts cannot invent token precision that packages/nextscript/src/4-generate.ts never recorded.

If you want, I can sketch the smallest refactor to packages/nextscript/src/4-generate.ts that introduces source-backed fragment writes without rewriting the whole printer.
 * 
 */


type Position = {
  line: number
  column: number
}

export function codeMappingsToSourceMap(sourceFile: string, generatedFile: string, source: string, generated: string, mappings: CodeMapping[]): EncodedSourceMap {
  const map = new GenMapping({ file: generatedFile })
  const sourceLineStarts = getLineStarts(source)
  const generatedLineStarts = getLineStarts(generated)

  setSourceContent(map, sourceFile, source)

  for (const mapping of mappings) {
    const generatedLengths = mapping.generatedLengths ?? mapping.lengths
    const count = Math.min(
      mapping.sourceOffsets.length,
      mapping.generatedOffsets.length,
      mapping.lengths.length,
      generatedLengths.length
    )

    for (let index = 0; index < count; index++) {
      const sourceOffset = mapping.sourceOffsets[index]
      const generatedOffset = mapping.generatedOffsets[index]
      const sourceLength = mapping.lengths[index]
      const generatedLength = generatedLengths[index]

      if (sourceLength <= 0 || generatedLength <= 0) continue

      addSpanBoundarySegments(
        map,
        sourceFile,
        sourceLineStarts,
        generatedLineStarts,
        sourceOffset,
        generatedOffset,
        sourceLength,
        generatedLength,
        source
      )
    }
  }

  return toEncodedMap(map)
}

function addSpanBoundarySegments(
  map: GenMapping,
  sourceFile: string,
  sourceLineStarts: number[],
  generatedLineStarts: number[],
  sourceOffset: number,
  generatedOffset: number,
  sourceLength: number,
  generatedLength: number,
  sourceContent: string
) {
  addOffsetSegment(map, sourceFile, sourceLineStarts, generatedLineStarts, sourceOffset, generatedOffset, sourceContent)

  if (generatedLength === 1 || sourceLength === 1) return

  const generatedEndOffset = generatedOffset + generatedLength - 1
  const sourceEndOffset = sourceOffset + sourceLength - 1

  if (generatedEndOffset > generatedOffset && sourceEndOffset > sourceOffset) {
    addOffsetSegment(map, sourceFile, sourceLineStarts, generatedLineStarts, sourceEndOffset, generatedEndOffset, sourceContent)
  }
}

function addOffsetSegment(
  map: GenMapping,
  sourceFile: string,
  sourceLineStarts: number[],
  generatedLineStarts: number[],
  sourceOffset: number,
  generatedOffset: number,
  sourceContent: string
) {
  const generatedPosition = offsetToPosition(generatedOffset, generatedLineStarts)
  const sourcePosition = offsetToPosition(sourceOffset, sourceLineStarts)

  maybeAddSegment(
    map,
    generatedPosition.line,
    generatedPosition.column,
    sourceFile,
    sourcePosition.line,
    sourcePosition.column,
    null,
    sourceContent
  )
}

function getLineStarts(text: string) {
  const lineStarts = [0]

  for (let index = 0; index < text.length; index++) {
    if (text.charCodeAt(index) === 10) {
      lineStarts.push(index + 1)
    }
  }

  return lineStarts
}

function offsetToPosition(offset: number, lineStarts: number[]): Position {
  let low = 0
  let high = lineStarts.length - 1

  while (low <= high) {
    const middle = (low + high) >> 1
    const lineStart = lineStarts[middle]
    const nextLineStart = lineStarts[middle + 1] ?? Number.POSITIVE_INFINITY

    if (offset < lineStart) {
      high = middle - 1
      continue
    }

    if (offset >= nextLineStart) {
      low = middle + 1
      continue
    }

    return {
      line: middle,
      column: offset - lineStart
    }
  }

  const lastLine = lineStarts.length - 1
  return {
    line: lastLine,
    column: Math.max(0, offset - lineStarts[lastLine])
  }
}