packages:
  - packages/*
  - plugins/*
  - websites/*
  - apps/*
  - demos
  - demos/*
  - e2e
  - e2e/*

overrides:
  postcss@<8.5.10: '>=8.5.10'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
