packages:
  - packages/**
  - plugins/**
  - .jungle/**
  - apps/**
  - demos/**
  - e2e/**

ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
