/**
 * Generated by GPT-5.4
 * 
 * script is currently unused. To restore, replace scripts with:
 *    "build:server": "node ./scripts/build.mjs build-server",
      "build:server-assets": "node ./scripts/build.mjs build-server-assets",
      "build:extension": "node ./scripts/build.mjs build-extension",
      "build:vendor": "node ./scripts/build.mjs build-vendor",
 */
import { cpSync, existsSync, mkdirSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { createRequire } from 'node:module'
import { build } from 'esbuild'

const require = createRequire(import.meta.url)
const scriptDir = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(scriptDir, '..')
const outDir = join(packageRoot, 'out')
const vendorDir = join(packageRoot, 'vendor_node_modules')

function resolvePackageRoot(name) {
  try {
    return dirname(require.resolve(`${name}/package.json`))
  } catch {
    let current = dirname(resolveImport(name))

    while (current !== dirname(current)) {
      if (existsSync(join(current, 'package.json'))) {
        return current
      }

      current = dirname(current)
    }

    throw new Error(`Could not find package root for ${name}`)
  }
}

function resolveImport(name) {
  return require.resolve(name)
}

function resetDir(path) {
  rmSync(path, { recursive: true, force: true })
  mkdirSync(path, { recursive: true })
}

function copyFile(from, to) {
  mkdirSync(dirname(to), { recursive: true })
  cpSync(from, to)
}

function copyDir(from, to) {
  mkdirSync(dirname(to), { recursive: true })
  rmSync(to, { recursive: true, force: true })
  cpSync(from, to, { recursive: true })
}

async function buildServer() {
  resetDir(outDir)

  await build({
    absWorkingDir: packageRoot,
    entryPoints: [resolve(packageRoot, '..', 'volar-noriscript', 'src', 'index.ts')],
    bundle: true,
    platform: 'node',
    format: 'esm',
    banner: {
      js: "import { createRequire as __rueCreateRequire } from 'node:module'; const require = __rueCreateRequire(import.meta.url);",
    },
    outfile: join(outDir, 'noriscript-language-server.mjs'),
    alias: {
      '@luently/noriscript/transpile': resolve(packageRoot, '..', '..', 'packages', 'noriscript', 'dist', 'transpile.mjs'),
      '@volar/language-core': resolvePackageRoot('@volar/language-core'),
      '@volar/language-server/node': resolveImport('@volar/language-server/node'),
      'volar-service-css': resolveImport('volar-service-css'),
      'volar-service-typescript': resolveImport('volar-service-typescript'),
      'vscode-uri': resolveImport('vscode-uri'),
    },
    logLevel: 'info',
  })
}

async function buildExtension() {
  await build({
    absWorkingDir: packageRoot,
    entryPoints: ['./src/extension.ts'],
    bundle: true,
    platform: 'node',
    format: 'cjs',
    external: ['vscode'],
    outfile: join(outDir, 'extension.js'),
    logLevel: 'info',
  })
}

function buildServerAssets() {
  const cssLanguageServiceRoot = resolvePackageRoot('vscode-css-languageservice')
  const cssUmdRoot = join(cssLanguageServiceRoot, 'lib', 'umd')

  mkdirSync(join(outDir, 'node_modules', '@oxc-parser'), { recursive: true })
  mkdirSync(join(outDir, 'node_modules', '@vscode'), { recursive: true })

  copyFile(join(cssUmdRoot, 'cssLanguageTypes.js'), join(outDir, 'cssLanguageTypes.js'))
  copyDir(join(cssUmdRoot, 'beautify'), join(outDir, 'beautify'))
  copyDir(join(cssUmdRoot, 'data'), join(outDir, 'data'))
  copyDir(join(cssUmdRoot, 'languageFacts'), join(outDir, 'languageFacts'))
  copyDir(join(cssUmdRoot, 'parser'), join(outDir, 'parser'))
  copyDir(join(cssUmdRoot, 'services'), join(outDir, 'services'))
  copyDir(join(cssUmdRoot, 'utils'), join(outDir, 'utils'))

  copyDir(resolvePackageRoot('@vscode/l10n'), join(outDir, 'node_modules', '@vscode', 'l10n'))
  copyDir(resolvePackageRoot('vscode-uri'), join(outDir, 'node_modules', 'vscode-uri'))
  copyDir(resolvePackageRoot('vscode-languageserver-textdocument'), join(outDir, 'node_modules', 'vscode-languageserver-textdocument'))
  copyDir(resolvePackageRoot('vscode-languageserver-types'), join(outDir, 'node_modules', 'vscode-languageserver-types'))
  copyDir(resolvePackageRoot('@oxc-parser/binding-darwin-arm64'), join(outDir, 'node_modules', '@oxc-parser', 'binding-darwin-arm64'))
}

function buildVendor() {
  resetDir(vendorDir)

  copyDir(resolvePackageRoot('@oxc-parser/binding-darwin-arm64'), join(vendorDir, '@oxc-parser', 'binding-darwin-arm64'))
  copyDir(resolvePackageRoot('@vscode/l10n'), join(vendorDir, '@vscode', 'l10n'))
  copyDir(resolvePackageRoot('vscode-uri'), join(vendorDir, 'vscode-uri'))
  copyDir(resolvePackageRoot('vscode-languageserver-textdocument'), join(vendorDir, 'vscode-languageserver-textdocument'))
  copyDir(resolvePackageRoot('vscode-languageserver-types'), join(vendorDir, 'vscode-languageserver-types'))
}

const command = process.argv[2]

try {
  switch (command) {
    case 'build-server':
      await buildServer()
      break
    case 'build-extension':
      await buildExtension()
      break
    case 'build-server-assets':
      buildServerAssets()
      break
    case 'build-vendor':
      buildVendor()
      break
    default:
      console.error(`Unknown build command: ${command}`)
      process.exit(1)
  }
} catch (error) {
  console.error(error)
  process.exit(1)
}